homepage: "https://github.com/dilithion/dilithion"
main_repo: "https://github.com/dilithion/dilithion.git"
language: c++
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
  - undefined
  - memory
architectures:
  - x86_64
maintainers:
  - "team@dilithion.org"
primary_contact: "team@dilithion.org"
auto_ccs:
  - "team@dilithion.org"
